---
- name: Install the latest httpd.
  yum: name={{ item }} state=latest
  with_items:
  - httpd
  - libsemanage-python
  - libselinux-python

- name: Insert iptables rules for httpd.
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp={{ httpd_port }} insertafter="^:OUTPUT"
              line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
  notify: restart iptables

- name: Enable httpd service
  service: name=httpd state=started enabled=yes

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes 
#  when: sestatus.rc != 0

- name: Create the index.html file
  template: src=index.html.j2 dest=/var/www/html/index.html
